// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/phillarson-xyz/pulumi-supavisor-native/sdk/go/supavisor-native/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The JWT secret
func GetJwtSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "supavisor-native:jwtSecret")
}
