// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SUPAVISOR_NATIVE
{
    /// <summary>
    /// The provider type for the SupavisorNative package.
    /// </summary>
    [SUPAVISOR_NATIVEResourceType("pulumi:providers:supavisor-native")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("supavisor-native", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/phillarson-xyz/pulumi-supavisor-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("jwtSecret")]
        private Input<string>? _jwtSecret;

        /// <summary>
        /// The SupavisorNative JWT secret.
        /// </summary>
        public Input<string>? JwtSecret
        {
            get => _jwtSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _jwtSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProviderArgs()
        {
            JwtSecret = Utilities.GetEnv("SUPAVISOR_NATIVE_JWT_SECRET");
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
