// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SUPAVISOR_NATIVE.Tenants.Outputs
{

    [OutputType]
    public sealed class User
    {
        /// <summary>
        /// Database password
        /// </summary>
        public readonly string DbPassword;
        /// <summary>
        /// Database user
        /// </summary>
        public readonly string DbUser;
        /// <summary>
        /// Database user alias
        /// </summary>
        public readonly string? DbUserAlias;
        public readonly string? Id;
        public readonly string? InsertedAt;
        /// <summary>
        /// The users who can be used for internal needs
        /// </summary>
        public readonly bool? IsManager;
        /// <summary>
        /// Max clients count
        /// </summary>
        public readonly int? MaxClients;
        /// <summary>
        /// Pooling mode type
        /// </summary>
        public readonly string? ModeType;
        /// <summary>
        /// Pool checkout timeout
        /// </summary>
        public readonly int? PoolCheckoutTimeout;
        /// <summary>
        /// Pool size
        /// </summary>
        public readonly int PoolSize;
        /// <summary>
        /// External Tenant ID
        /// </summary>
        public readonly string? TenantExternalId;
        public readonly string? UpdatedAt;

        [OutputConstructor]
        private User(
            string dbPassword,

            string dbUser,

            string? dbUserAlias,

            string? id,

            string? insertedAt,

            bool? isManager,

            int? maxClients,

            string? modeType,

            int? poolCheckoutTimeout,

            int poolSize,

            string? tenantExternalId,

            string? updatedAt)
        {
            DbPassword = dbPassword;
            DbUser = dbUser;
            DbUserAlias = dbUserAlias;
            Id = id;
            InsertedAt = insertedAt;
            IsManager = isManager;
            MaxClients = maxClients;
            ModeType = modeType;
            PoolCheckoutTimeout = poolCheckoutTimeout;
            PoolSize = poolSize;
            TenantExternalId = tenantExternalId;
            UpdatedAt = updatedAt;
        }
    }
}
