// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("supavisor-native");

/**
 * The JWT secret
 */
export declare const jwtSecret: string | undefined;
Object.defineProperty(exports, "jwtSecret", {
    get() {
        return __config.get("jwtSecret");
    },
    enumerable: true,
});

