// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export namespace tenants {
    export interface TenantPropertiesArgs {
        /**
         * List of CIDR addresses
         */
        allowList?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * SELECT rolname, rolpassword FROM pg_authid WHERE rolname=$1
         */
        authQuery?: pulumi.Input<string>;
        /**
         * Database name
         */
        dbDatabase: pulumi.Input<string>;
        /**
         * Database host
         */
        dbHost: pulumi.Input<string>;
        /**
         * Database port
         */
        dbPort: pulumi.Input<number>;
        enforceSsl?: pulumi.Input<boolean>;
        /**
         * External ID
         */
        externalId?: pulumi.Input<string>;
        id?: pulumi.Input<string>;
        insertedAt?: pulumi.Input<string>;
        /**
         * auto
         */
        ipVersion?: pulumi.Input<string>;
        requireUser: pulumi.Input<boolean>;
        /**
         * your.domain.com
         */
        sniHostname?: pulumi.Input<string>;
        updatedAt?: pulumi.Input<string>;
        upstreamSsl?: pulumi.Input<boolean>;
        /**
         * none
         */
        upstreamVerify?: pulumi.Input<string>;
        users: pulumi.Input<pulumi.Input<inputs.tenants.UserArgs>[]>;
    }
    /**
     * tenantPropertiesArgsProvideDefaults sets the appropriate defaults for TenantPropertiesArgs
     */
    export function tenantPropertiesArgsProvideDefaults(val: TenantPropertiesArgs): TenantPropertiesArgs {
        return {
            ...val,
            enforceSsl: (val.enforceSsl) ?? false,
            requireUser: (val.requireUser) ?? false,
            upstreamSsl: (val.upstreamSsl) ?? true,
        };
    }

    export interface UserArgs {
        /**
         * Database password
         */
        dbPassword: pulumi.Input<string>;
        /**
         * Database user
         */
        dbUser: pulumi.Input<string>;
        /**
         * Database user alias
         */
        dbUserAlias?: pulumi.Input<string>;
        id?: pulumi.Input<string>;
        insertedAt?: pulumi.Input<string>;
        /**
         * The users who can be used for internal needs
         */
        isManager?: pulumi.Input<boolean>;
        /**
         * Max clients count
         */
        maxClients?: pulumi.Input<number>;
        /**
         * Pooling mode type
         */
        modeType?: pulumi.Input<string>;
        /**
         * Pool checkout timeout
         */
        poolCheckoutTimeout?: pulumi.Input<number>;
        /**
         * Pool size
         */
        poolSize: pulumi.Input<number>;
        /**
         * External Tenant ID
         */
        tenantExternalId?: pulumi.Input<string>;
        updatedAt?: pulumi.Input<string>;
    }
}
