// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getTenant(args: GetTenantArgs, opts?: pulumi.InvokeOptions): Promise<outputs.tenants.Tenant> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("supavisor-native:tenants:getTenant", {
        "externalId": args.externalId,
    }, opts);
}

export interface GetTenantArgs {
    /**
     * External ID of the tenant
     */
    externalId: string;
}
export function getTenantOutput(args: GetTenantOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<outputs.tenants.Tenant> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("supavisor-native:tenants:getTenant", {
        "externalId": args.externalId,
    }, opts);
}

export interface GetTenantOutputArgs {
    /**
     * External ID of the tenant
     */
    externalId: pulumi.Input<string>;
}
